@startuml uc-nghiep-vu-tong
!pragma layout smetana
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 16
skinparam monochrome true
skinparam shadowing false
skinparam dpi 170
skinparam stereotypeFontSize 14
left to right direction

actor/ "Khách hàng" as KH <<business actor>>
actor/ "Đơn vị\nvận chuyển" as VC <<business actor>>
actor/ "Nhà cung cấp" as NCC <<business actor>>
actor/ "Trung tâm\nbảo hành hãng" as TTBH <<business actor>>
actor/ "Chủ cửa hàng" as CCH <<business actor>>

rectangle "Hệ thống bán hàng điện gia dụng của cửa hàng" {
  usecase/ "Giới thiệu sản phẩm\nvà khuyến mãi" as B1
  usecase/ "Bán hàng" as B2
  usecase/ "Giao hàng" as B3
  usecase/ "Lắp đặt tận nơi" as B8
  usecase/ "Đổi trả hàng" as B4
  usecase/ "Bảo hành sản phẩm" as B6
  usecase/ "Kiểm tra máy\ntheo số serial" as B9
  usecase/ "Nhập hàng" as B5
  usecase/ "Lập báo cáo\nkinh doanh" as B7
}

KH -- B1
KH -- B2
KH -- B3
KH -- B4
KH -- B6
B3 --- VC
B6 --- TTBH
B5 --- NCC
B7 --- CCH

B8 .> B3 : <<extend>>
B4 ..> B9 : <<include>>
B6 ..> B9 : <<include>>
@enduml
